/*
* Copyright 2019 Nu-book Inc.
* Copyright 2023 Axel Waggershauser
*/
// SPDX-License-Identifier: Apache-2.0

#pragma once

// micro-zxing: this file is normally generated by the upstream CMake build from
// `core/Version.h.in`. It is provided here as a shim because PlatformIO does not
// run CMake. It is exposed on the include path via tools/gen_zxing_version.py.
// Keep it in sync with the submodule tag in lib/zxing/src when updating.

#define ZXING_READERS
// ZXING_WRITERS intentionally NOT defined: this project only reads barcodes.
// (Enabling the writer would also pull in the zint backend via ZXING_USE_ZINT.)

// Enable all supported formats (matches the upstream CMake defaults).
#define ZXING_ENABLE_1D 1
#define ZXING_ENABLE_AZTEC 1
#define ZXING_ENABLE_DATAMATRIX 1
#define ZXING_ENABLE_MAXICODE 1
#define ZXING_ENABLE_PDF417 1
#define ZXING_ENABLE_QRCODE 1

// Version numbering
#define ZXING_VERSION_MAJOR 3
#define ZXING_VERSION_MINOR 1
#define ZXING_VERSION_PATCH 1
#define ZXING_VERSION_SUFFIX ""

#define ZXING_VERSION_STR "3.1.1"
