/*
* Copyright 2019 Nu-book Inc.
* Copyright 2023 Axel Waggershauser
*/
// SPDX-License-Identifier: Apache-2.0

#pragma once

// micro-zxing: this file is normally generated by the upstream CMake build from
// `core/Version.h.in`. It is provided here as a shim because PlatformIO does not
// run CMake. The compiler finds it because `lib/zxing` is added to the include path
// (see the "-Ilib/zxing" flag in library.json).
// Keep it in sync with the submodule tag in lib/zxing/src when updating.

#define ZXING_READERS
#define ZXING_WRITERS

// Version numbering
#define ZXING_VERSION_MAJOR 2
#define ZXING_VERSION_MINOR 3
#define ZXING_VERSION_PATCH 0

#define ZXING_VERSION_STR "2.3.0"
