/*
 * Copyright 2019 Nu-book Inc.
 * Copyright 2023 Axel Waggershauser
 */
// SPDX-License-Identifier: Apache-2.0

#pragma once

// This header mirrors the `Version.h` that is normally generated by the upstream
// zxing-cpp CMake build (see lib/zxing/core/CMakeLists.txt + lib/zxing/core/Version.h.in).
// Because micro-zxing builds the submodule sources directly (no CMake preprocessing),
// this file is kept in sync manually with the checked-out lib/zxing submodule.
//
// Configuration kept in sync with the upstream CMake defaults:
//   - readers: enabled  (ZXING_READERS)
//   - writers: disabled (ZXING_WRITERS and ZXING_USE_ZINT are NOT defined)
//   - all barcode formats: enabled
//
// When you update the lib/zxing submodule:
//   1. update ZXING_VERSION_* below (version is taken from core/CMakeLists.txt
//      `project(ZXing VERSION "...")`), and
//   2. review the ZXING_ENABLE_* macros against core/Version.h.in / core/CMakeLists.txt.

#define ZXING_READERS

#define ZXING_ENABLE_1D 1
#define ZXING_ENABLE_AZTEC 1
#define ZXING_ENABLE_DATAMATRIX 1
#define ZXING_ENABLE_MAXICODE 1
#define ZXING_ENABLE_PDF417 1
#define ZXING_ENABLE_QRCODE 1

// Version numbering
#define ZXING_VERSION_MAJOR 3
#define ZXING_VERSION_MINOR 1
#define ZXING_VERSION_PATCH 1
#define ZXING_VERSION_SUFFIX ""

#define ZXING_VERSION_STR "3.1.1"
